"""empty message

Revision ID: 29c04d5fc2ab
Revises: 55277c5ac049
Create Date: 2024-01-24 23:39:24.970612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c04d5fc2ab'
down_revision = '55277c5ac049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privilage_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='user'
    )
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type'),
    schema='user'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('nic', sa.String(length=128), nullable=False),
    sa.Column('create_user_id', sa.Integer(), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['create_user_id'], ['user.user.id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user.user_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nic'),
    sa.UniqueConstraint('user_name'),
    schema='user'
    )
    op.create_table('create_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('privilage_entity_id', sa.Integer(), nullable=False),
    sa.Column('create_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['create_user_id'], ['user.user.id'], ),
    sa.ForeignKeyConstraint(['privilage_entity_id'], ['user.privilage_entity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='user'
    )
    op.create_table('delete_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('privilage_entity_id', sa.Integer(), nullable=False),
    sa.Column('create_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['create_user_id'], ['user.user.id'], ),
    sa.ForeignKeyConstraint(['privilage_entity_id'], ['user.privilage_entity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='user'
    )
    op.create_table('edit_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('privilage_entity_id', sa.Integer(), nullable=False),
    sa.Column('create_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['create_user_id'], ['user.user.id'], ),
    sa.ForeignKeyConstraint(['privilage_entity_id'], ['user.privilage_entity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='user'
    )
    op.create_table('view_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('privilage_entity_id', sa.Integer(), nullable=False),
    sa.Column('create_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['create_user_id'], ['user.user.id'], ),
    sa.ForeignKeyConstraint(['privilage_entity_id'], ['user.privilage_entity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='user'
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('view_access', schema='user')
    op.drop_table('edit_access', schema='user')
    op.drop_table('delete_access', schema='user')
    op.drop_table('create_access', schema='user')
    op.drop_table('user', schema='user')
    op.drop_table('user_type', schema='user')
    op.drop_table('privilage_entity', schema='user')
    # ### end Alembic commands ###
