"""empty message

Revision ID: 55277c5ac049
Revises: 4430ed387d5f
Create Date: 2024-01-24 23:36:46.832760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55277c5ac049'
down_revision = '4430ed387d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
