"""empty message

Revision ID: 752821d73f5e
Revises: 16c7452c32c4
Create Date: 2024-01-25 00:12:34.865288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752821d73f5e'
down_revision = '16c7452c32c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
