#Models have to be define here to get registered while migration
from ..models.store import StoreModel
from ..models.item import ItemModel
from ..models.tag import TagModel
from ..models.item_tags import ItemTags
from .user_old import UserModel
from .customer import CustomerModel
from .user import UserModel2
from .user import UserTypeModel
from .user import CreateAccessModel
from .user import DeleteAccessModel
from .user import ViewAccessModel
from .user import EditAccessModel
from .user import PrivilageEntityModel
from .food import FoodModel
from .food import FoodCategoryModel
from .food import FoodPortionTypeModel
from .food import MapFoodFoodCategoryModel
from .food import MapFoodFoodPortionTypeModel
from .order import OrderModel
from .order import OrderStatusModel
from .order import OrderTypeModel
from .order import DiscountTypeModel
from .order import PaymentTypeModel
from .order import MapOrderFoodModel
